[package]
name = "oidn"
version = "0.1.0"
authors = ["Will Usher <will@willusher.io>"]
build = "build.rs"
homepage = "https://github.com/Twinklebear/oidn-rs"
documentation = "https://github.com/Twinklebear/oidn-rs"
repository = "https://github.com/Twinklebear/oidn-rs"
readme = "README.md"
license = "MIT"
description = """
A wrapper for the Intel OpenImageDenoise image denoising library.
"""
keywords = ["openimagedenoise", "denoise", "denoising"]
exclude = [
	".travis.yml",
	"*.png",
	".gitignore",
	"examples/*"
]

